baseURL = "https://juananpe.github.io/genai-crew/"
languageCode = "en-us"
title = "GenAI Crew"
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = true
buildFuture = false
buildExpired = false

[minify]
disableXML = true
minifyOutput = true

[pagination]
  pagerSize = 4 # Set the number of posts to show before overflowing to the next page.
summaryLength = 10 # Configure how long the post summary should be on the homepage.

# Add your Google Analytics identifier: UA-XXXXXXXX-X
googleAnalytics = "" 

# Add your Disqus shortname here.
disqusShortname = ""    

[taxonomies]
  tag = "tags"

# Set to false to disallow raw HTML in markdown files
[markup.goldmark.renderer]
    unsafe = true

[params]
  # types of posts to be listed on the home page
  mainSections = ["post"]

  # Turn on LaTeX support
	math = true
	# Blog description at the top of the homepage. Supports markdown.
	description = "A collection of GenAI-related posts"

    showReadMore = false

    # Set enableKofi to true to enable the Ko-fi support button. Add your Ko-fi ID to link to your account.
    enableKofi = false
    kofi = ""

	# Add links to your accounts. Remove the ones you don't want to include.
	# Main
	email = "#"
    facebook = "#"
    twitter = "#"
	instagram = "#"
	tumblr = "#"
	reddit = "#"
	pinterest = "#"
	youtube = "#"
    vimeo = "#"
	weibo = "#"
	vk = "#"
	linkedin = "#"

	# Writing
    medium = "#"
	blogger = "#"
	wordpress = "#"

	# Creative & Visual
    dribbble = "#"
	behance = "#"
	deviantart = "#"
	flickr = "#"

    # Audio & Music
    soundcloud = "#"

	# Programming
    github = "#"
	stackoverflow = "#"
	gitlab = "#"
	codepen = "#"

    # Academic
    googlescholar = "#"
    impactstory = "#"
    orcid = "#"  

  text_color = ""
  favicon = ""
  site_logo = ""
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

# Menu links along the sidebar navigation.
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 20

# [[menu.main]]
#   name = "Archives"
#   identifier = "archives"
#   url = "archives/"
#   weight = 3

# Privacy configurations: https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

# Add the new author configuration under [params]
[params]
author = "GenAI Crew"
