baseURL = "https://juananpe.github.io/genai-crew/"
languageCode = "en-us"
title = "GenAI Crew"
theme = "ananke"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "A collection of GenAI-related posts"
  background_color_class = "bg-black"
  recent_posts_number = 3

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[minify]
disableXML = true
minifyOutput = true

[pagination]
  pagerSize = 4 # Set the number of posts to show before overflowing to the next page.
summaryLength = 10 # Configure how long the post summary should be on the homepage.

# Add your Google Analytics identifier: UA-XXXXXXXX-X
googleAnalytics = "" 

# Add your Disqus shortname here.
disqusShortname = ""    

[taxonomies]
  tag = "tags"

# Set to false to disallow raw HTML in markdown files
[markup.goldmark.renderer]
    unsafe = true

[params]
env = "production"
title = "GenAI Crew"
keywords = [ "Blog", "Portfolio", "GenAI" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true

[params.homeInfoParams]
Title = "Welcome to GenAI Crew 👋"
Content = "A collection of posts about Generative AI and related topics"

[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 20

# [[menu.main]]
#   name = "Archives"
#   identifier = "archives"
#   url = "archives/"
#   weight = 3

# Privacy configurations: https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
